site_name: Ozzy Documentation
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: pink

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink

  font:
    text: Atkinson Hyperlegible
    code: Roboto Mono

  features:
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer

markdown_extensions:
  - admonition
  - footnotes
  - abbr
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/mtrocadomoreira/ozzy

repo_url: https://github.com/mtrocadomoreira/ozzy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: [ozzy]
          options:
            show_source: false
            show_root_heading: true
            docstring_style: numpy
          import:
          - https://docs.xarray.dev/en/stable/objects.inv
          - https://docs.dask.org/en/stable/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
  # - git-revision-date-localized:
  #   enabled: !ENV [CI, false]
  #   enable_creation_date: true
  #   fallback_to_build_date: true
  # - privacy:
  #   enabled: !ENV [CI, false]


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Page tree
nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - Installation: user-guide/installation.md
    - Getting started: user-guide/getting-started.md
    - Key Concepts: user-guide/key-concepts.md
    - Reading files: user-guide/reading-files.md
    - Plotting: user-guide/plotting.md
    - Analysis: user-guide/analysis.md
    - Notes on speed: user-guide/speed.md
    - See also: user-guide/see-also.md
  - Code Reference: 
    - reference/index.md
    - Core: reference/core.md
    - Data Objects: reference/data-objects.md
    - Backends: reference/backends.md
    - ozzy.plot: reference/plot.md
    - ozzy.statistics: reference/statistics.md
    - ozzy.fields: reference/fields.md
  - Developer Guide:
    - dev-guide/index.md
  - About: 
      - about/index.md
      - License: about/license.md
#     - Installation: getting-started.md
#     - Creating your site: creating-your-site.md
#     - Publishing your site: publishing-your-site.md
#     - Customization: customization.md
#     - Conventions: conventions.md
#     - Browser support: browser-support.md
#     - Enterprise feedback: enterprise-support.md
#     - Philosophy: philosophy.md
#     - Alternatives: alternatives.md
#     - License: license.md
#     - Changelog:
#       - changelog/index.md
#       - How to upgrade: upgrade.md
#   - Setup:
#     - setup/index.md
#     - Changing the colors: setup/changing-the-colors.md
#     - Changing the fonts: setup/changing-the-fonts.md
#     - Changing the language: setup/changing-the-language.md
#     - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#     - Ensuring data privacy: setup/ensuring-data-privacy.md
#     - Setting up navigation: setup/setting-up-navigation.md
#     - Setting up site search: setup/setting-up-site-search.md
#     - Setting up site analytics: setup/setting-up-site-analytics.md
#     - Setting up social cards: setup/setting-up-social-cards.md
#     - Setting up a blog: setup/setting-up-a-blog.md
#     - Setting up tags: setup/setting-up-tags.md
#     - Setting up versioning: setup/setting-up-versioning.md
#     - Setting up the header: setup/setting-up-the-header.md
#     - Setting up the footer: setup/setting-up-the-footer.md
#     - Adding a git repository: setup/adding-a-git-repository.md
#     - Adding a comment system: setup/adding-a-comment-system.md
#     - Building an optimized site: setup/building-an-optimized-site.md
#     - Building for offline usage: setup/building-for-offline-usage.md
#     - Extensions:
#       - setup/extensions/index.md
#       - Python Markdown: setup/extensions/python-markdown.md
#       - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
#   - Plugins:
#     - plugins/index.md
#     - Blog: plugins/blog.md
#     - Group: plugins/group.md
#     - Info: plugins/info.md
#     - Meta: plugins/meta.md
#     - Offline: plugins/offline.md
#     - Optimize: plugins/optimize.md
#     - Privacy: plugins/privacy.md
#     - Projects: plugins/projects.md
#     - Search: plugins/search.md
#     - Social: plugins/social.md
#     - Tags: plugins/tags.md
#     - Typeset: plugins/typeset.md
#     - Requirements:
#       - Image processing: plugins/requirements/image-processing.md
#       - Caching: plugins/requirements/caching.md
#   - Reference:
#     - reference/index.md
#     - Admonitions: reference/admonitions.md
#     - Annotations: reference/annotations.md
#     - Buttons: reference/buttons.md
#     - Code blocks: reference/code-blocks.md
#     - Content tabs: reference/content-tabs.md
#     - Data tables: reference/data-tables.md
#     - Diagrams: reference/diagrams.md
#     - Footnotes: reference/footnotes.md
#     - Formatting: reference/formatting.md
#     - Grids: reference/grids.md
#     - Icons, Emojis: reference/icons-emojis.md
#     - Images: reference/images.md
#     - Lists: reference/lists.md
#     - Math: reference/math.md
#     - Tooltips: reference/tooltips.md
#   - Insiders:
#     - insiders/index.md
#     - Getting started: insiders/getting-started.md
#     - FAQ: insiders/faq/sponsoring.md
#     - Changelog:
#       - insiders/changelog/index.md
#       - How to upgrade: insiders/upgrade.md
#   - Community:
#     - Contributing:
#       - contributing/index.md
#       - Reporting a bug: contributing/reporting-a-bug.md
#       - Reporting a docs issue: contributing/reporting-a-docs-issue.md
#       - Requesting a change: contributing/requesting-a-change.md
#       - Adding translations: contributing/adding-translations.md
#       - Making a pull request: contributing/making-a-pull-request.md
#       - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
#     - Guides:
#       - Creating a reproduction: guides/creating-a-reproduction.md
#     - Community experts program:
#       - insiders/community-experts-program/index.md
#   - Blog:
#     - blog/index.md



    
    
  
