site_name: Ozzy Documentation
site_url: https://mtrocadomoreira.github.io/ozzy/
copyright: Copyright &copy; 2024 Mariana Moreira
# copyright: >
#   Copyright &copy; 2024 Mariana Moreira –
#   <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  custom_dir: overrides
  logo: assets/ozzy_icon_dark.svg
  favicon: assets/ozzy_icon.svg
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom

  font:
    text: Atkinson Hyperlegible
    code: Roboto Mono

  features:
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - abbr
  - toc:
      permalink: §
      permalink_title: Link to this section
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
        - "./"
      check_paths: false
      url_download: false
      url_max_size: 33554432
      url_timeout: 10
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/mtrocadomoreira/ozzy
extra:
  status:
    in-progress: Page under development
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  #   actions:
  #    - accept
  #    - manage
  #    - reject
  # analytics:
  #   provider: google
  #   property: ozzy-documentation
  #     feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/mtrocadomoreira/ozzy

plugins:
  - search
 # - privacy # mathjax equations are not rendered correctly when this is active
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: ['../src']
          options:
            show_source: false
            show_root_heading: false
            docstring_style: numpy
            parameter_headings: true
            show_inheritance_diagram: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_root_members_full_path: false
            show_category_heading: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # members_order: source
            inherited_members: true
            docstring_section_style: table
            separate_signature: true
            heading_level: 3
          import:
          - https://docs.xarray.dev/en/stable/objects.inv
          - https://docs.dask.org/en/stable/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
          - https://docs.h5py.org/en/stable//objects.inv

  - git-revision-date-localized:
      enabled: true #!ENV [CI, false]
      enable_creation_date: true
      fallback_to_build_date: true
  # - privacy:
  #   enabled: !ENV [CI, false]

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - Installation:
      - user-guide/installation/index.md
      - Virtual environment setup: user-guide/installation/virtual-environments.md
    - Getting started: user-guide/getting-started.md
    - Key Concepts: user-guide/key-concepts.md
    - Reading files: user-guide/reading-files.md
    - Plotting: user-guide/plotting.md
    - Analysis: user-guide/analysis.md
    - Notes on speed: user-guide/speed.md
    - See also: user-guide/see-also.md
  - Code Reference: 
    - reference/index.md
    - ozzy: reference/core.md
    - Data object methods:
      - reference/data-objects/index.md
      - Data-type-specific methods: reference/data-objects/data-type-methods.md
      - Backend-specific methods: reference/data-objects/backend-methods.md
    - Backends: 
      - reference/backends/index.md
      - Submodules: 
        - reference/backends/submodules/index.md
        - LCODE: reference/backends/submodules/lcode.md
        - OSIRIS: reference/backends/submodules/osiris.md
        - Ozzy: reference/backends/submodules/ozzy.md
    - ozzy.plot: reference/plot.md
    - ozzy.statistics: reference/statistics.md
    - ozzy.fields: reference/fields.md
    - ozzy.utils: reference/utils.md
  # - Developer Guide:
  #   - dev-guide/index.md
  - About: 
      - about/index.md
      - License: about/license.md




    
    
  
